# Mandatory settings

name: THIS IS WK
paginate: 25
url: thisiswk.com
blog_theme: light # Or use dark
#baseurl: will use THIS IS WK . com

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: # Add your Disqus identifier
ga_analytics: UA-93560728-2
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false # Change to false if not
social:
  facebook: testarossa.k
  github: wangki
  linkedin: leewk
  email: wonkeun6@gmail.comm
#  twitter: # Add your Twitter handle
#  bitcoin: # Add your Bitcoin link or address
#  dribbble: # Add your Dribbble handle
#  flickr: # Add your Flickr handle



# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
